telephony: SmsMessage: Bring newFromCDS method back
04-07 07:52:44.272  2200  2200 E AndroidRuntime: FATAL EXCEPTION: main
04-07 07:52:44.272  2200  2200 E AndroidRuntime: Process: com.mediatek.ims, PID: 2200
04-07 07:52:44.272  2200  2200 E AndroidRuntime: java.lang.NoSuchMethodError: No static method newFromCDS([B)Lcom/android/internal/telephony/gsm/SmsMessage; in class Lcom/android/internal/telephony/gsm/SmsMessage; or its super classes (declaration of 'com.android.internal.telephony.gsm.SmsMessage' appears in /system/framework/framework.jar!classes4.dex)
04-07 07:52:44.272  2200  2200 E AndroidRuntime: 	at com.mediatek.ims.feature.MtkImsSmsImpl.newStatusReportInd(MtkImsSmsImpl.java:153)
04-07 07:52:44.272  2200  2200 E AndroidRuntime: 	at com.mediatek.ims.feature.MtkMmTelFeature$1.newStatusReportInd(MtkMmTelFeature.java:173)
04-07 07:52:44.272  2200  2200 E AndroidRuntime: 	at com.mediatek.ims.ImsService$MyHandler.handleMessage(ImsService.java:2606)
04-07 07:52:44.272  2200  2200 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-07 07:52:44.272  2200  2200 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
04-07 07:52:44.272  2200  2200 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
04-07 07:52:44.272  2200  2200 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
04-07 07:52:44.272  2200  2200 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-07 07:52:44.272  2200  2200 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
04-07 07:52:44.272  2200  2200 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

Change-Id: If37782879a9d9ddfac8283fa243858327ce78850
Signed-off-by: SamarV-121 <samarvispute121@pm.me>
Signed-off-by: Ghosuto <clash.raja10@gmail.com>