ThemeOverlayApplier: Catch a potential NPE.
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.om.OverlayIdentifier android.content.om.FabricatedOverlay.getIdentifier()' on a null object reference

Signed-off-by: spezi77 <spezi7713@gmx.net>
Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>
Signed-off-by: Ghosuto <clash.raja10@gmail.com>